---
title: "29.11.2022"
author: "Valéria"
date: "2022-11-29"
output: html_document
---

## Task 1
```{r}
x <- 5:75
x
```
```{r}
x1 <- 3.14; 2.71; 0; 13
x1
```
```{r}
x2 <- c(TRUE, 100)
x2
```
```{r}
x3 <- rep(TRUE, 100)
x3
```

```{r}
x = matrix(
  c(12, 34, 87, -12, -12.1, 0, 3.6, 0.5, 1.3),
  nrow=3, 
  ncol=3, 
  byrow = TRUE)
x
```
```{r}
list_var <- list(char_var, num_var, int_var, complex_var, logical_var)
list_var
```
```{r}
factor_var <- factor(c("infant", "child", "adult"))
factor_var
```
```{r}
data <- data.frame(
  id = 1:10,
  name = c("Anna", "Bruno", "Charlie", "Diana", "Erika", "Felix", "Gusto", "Hana", "Ivan", "Julia"),
  age = c(58, 25, 19, 24, 15, 43, 36, 21, 45, 38)
)
```
```{r}
colnames(data)<- c("ID", "Name", "Age")
data
```
##Task 2
```{r message=FALSE}
library(dplyr)

airquality |> 
  group_by(Month) |> 
  summarise(mean_temp = mean(Temp)) |> 
  filter(mean_temp == max(mean_temp))
```


```{r}
airquality <- read.csv("airquality.csv")
colnames(airquality)
rownames(airquality)
head(airquality, 6)
nrow(airquality)
tail(airquality, 6)
sum(is.na(airquality$0zone))
mean(airquality$0zone, na.rm = TRUE)
subset(airquality, 0zone>31&Temp>90)
```

```{r}
#Task2
library(dplyr)

#1
airquality |> 
  colnames()
  
#2
airquality |> 
  rownames()

#3
airquality |> 
slice(1:6)

#4
airquality |>
nrow()
Adriana
Adriana Aďa Malatincová
#5
airquality |>
filter(is.na(Ozone)) |>
nrow()


#6
airquality |>
filter(Ozone > 31 & Temp > 90) |>
print()


```

